### ISSUE TITLE
which OS to use on raspberry pi 3b+?

### ISSUE THREAD

**Issue by zoldaten** [linorobot/linorobot2#1]
i wonder which OS to install on raspberry pi 3b+ ?
i think of:
- Ubuntu Server 20.04.3 LTS  - https://ubuntu.com/download/raspberry-pi - 32-bit or 64-bit ,
- ubuntu mate https://ubuntu-mate.org/raspberry-pi/ - armhf (ARMv7 32-bit) and arm64 (ARMv8 64-bit) ,
- Raspbian ?

What do you recommend  and best suits to ROS2 ?

**Comment by grassjelly** [comment]
I havent tested on 3b+ maybe you could try Ubuntu Server 20 - 64 bit. Closing this as this is not a package related issue.
