### ISSUE TITLE
Problem with armv7 and docker osrf

### ISSUE THREAD

**Issue by tbop-R** [linorobot/linorobot2#108]
Hello everyone,
I have an armv7 card.
I made a build of a docker image starting from this git:
https://github.com/osrf/docker_images
Once the image was created, I tried compiling linorobot2
I cloned micro_ros_setup
I ran the command
rosdep install --from-path src --ignore-src -y
and I get the following error:

E: Unable to locate package ros-humble-fastcdr
ERROR: the following rosdeps failed to install
   apt: command [apt-get install -y ros-humble-fastcdr] failed
  
  
I don't understand why apt install is used.
ros2 on armv7 can only be compiled.
inside ws/src I have the following folders:
ament eProsima eclipse-cyclonedds eclipse-iceoryx ignition micro_ros_setup osrf ros ros-perception ros-planning ros-tooling ros-visualization ros2
I believe the addiction is there.
Where am I doing wrong?

**Comment by grassjelly** [comment]
have you tried this https://github.com/linorobot/linorobot2/tree/humble/docker ?
