### ISSUE TITLE
Sonar Sensors _ Obstruction Layer to linorobot2

### ISSUE THREAD

**Issue by hemsinghb** [linorobot/linorobot2#115]
Dear Sir,  
 I am writing to request the inclusion of a few ultrasound sonar range sensors in the linorobot2 hardware obstruction layer. Specifically, I would like two sensors added to the front, and one each added to the left, right, and back of the robot. These sensors will allow the robot to detect obstructions and emergencies, and take alternative paths where necessary.

Thank you for your attention to this matter.

Best regards,

Hems.

**Comment by grassjelly** [comment]
I'm afraid, I don't have the bandwidth to implement that now.
