### ISSUE TITLE
Humble install failure: ydlidar

### ISSUE THREAD

**Issue by tbalatka** [linorobot/linorobot2#116]
gmake[2]: *** [CMakeFiles/ydlidar_ros2_driver_node.dir/build.make:76: CMakeFiles/ydlidar_ros2_driver_node.dir/src/ydlidar_ros2_driver_node.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/ydlidar_ros2_driver_node.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< ydlidar_ros2_driver [9.19s, exited with code 2]

Summary: 9 packages finished [17.3s]
  1 package failed: ydlidar_ros2_driver
  1 package had stderr output: ydlidar_ros2_driver

**Comment by tbalatka** [comment]
Installs OK with using another lidar, example: "a1" (for RPLIDAR A1).

**Comment by grassjelly** [comment]
can you post the issue here please: https://github.com/YDLIDAR/YDLidar-SDK.git. Looks like a driver problem. Thanks! Closing this for now.
