### ISSUE TITLE
waypoint not properly working

### ISSUE THREAD

**Issue by raidhu** [linorobot/linorobot2#13]
`bt_navigator-7] [ERROR] [1637145018.446545161] [bt_navigator]: Action server failed while executing action callback: "send_goal failed"
[bt_navigator-7] [WARN] [1637145018.446705291] [bt_navigator]: [navigate_to_pose] [ActionServer] Aborting handle.
[controller_server-4] [INFO] [1637145018.470105004] [controller_server]: Passing new path to controller.
[waypoint_follower-8] [WARN] [1637145019.078624924] [waypoint_follower]: Failed to process waypoint 0 in waypoint list and stop on failure is enabled. Terminating action.
[waypoint_follower-8] [WARN] [1637145019.078847924] [waypoint_follower]: [FollowWaypoints] [ActionServer] Aborting handle.
[controller_server-4] [ERROR] [1637145026.420263585] [controller_server]: Failed to make progress
[controller_server-4] [WARN] [1637145026.420737567] [controller_server_rclcpp_node]: [follow_path] [ActionServer] Aborting handle.
`
this is the error I'm getting sometime when try to run waypoint follower.
navigation failed.
is it possible to save multiple waypoints. waypoints

**Comment by grassjelly** [comment]
Hi, this question is more related to Nav2. Please post this on ROS answers
