### ISSUE TITLE
could not choose the laser sensor.

### ISSUE THREAD

**Issue by retrodorian** [linorobot/linorobot2#134]
Hi, when I use the command "bash install_linorobot2.bash <robot_type> <laser_sensor> <depth_sensor>" as bash "install_linorobot2.bash 4wd" a1, (I do not have depth_sensor yet so I am not choosing any) the terminal output says that I should use rplidar etc. How the system will know the model of my LIDAR if I can only specify rplidar? Also foxy has lots of rosdep issues, do you advise me to keep use it? I am using rpi4 with 4GB RAM so I have some resource issues. Thank you for your interest.

**Comment by hippo5329** [comment]
Foxy is EOL. You should use Humble instead.

If you have to use Foxy, follow this wiki to install dependency.

https://github.com/hippo5329/linorobot2_hardware/wiki#install-linorobot2-on-ubuntu-2004-and-foxy

Then install linorobot2 with humble branch. It will work for Foxy.

```
cd /tmp
wget https://raw.githubusercontent.com/linorobot/linorobot2/humble/install_linorobot2.bash
bash install_linorobot2.bash 2wd a1
source ~/.bashrc
```

**Comment by hippo5329** [comment]
BTW, you can not execute commands with cut-and-paste in ubuntu 20.04 terminal. You will need to save the commands as a script and run the script. Otherwise, some commands will not be executed.

**Comment by retrodorian** [comment]
Thank you so much. I installed all dependencies manually.
