### ISSUE TITLE
unable to install Linorobot - YDLidar SDK missing folder

### ISSUE THREAD

**Issue by Rossobimbo** [linorobot/linorobot2#17]
HI Grassjelly,

when running "install_linorobot_2.bash" i get the following error

install_linorobot2.bash: line 62: cd: YDLidar-SDK/build: No such file or directory

i've also modified line 18 from ROSDISTRO="$(rosversion -d)" to ROSDISTRO="$(echo $ROS_DISTRO)" as otherwise it wouldn't recognize the distro version.

I've checked on YDLidar github, and the "build" folder is not longer there.

Any suggestion?

**Comment by grassjelly** [comment]
you found a bug! fixed it with this https://github.com/linorobot/linorobot2/commit/7a64f529dcd30f95e8c4c32dc32b665067fc85a3

**Comment by Rossobimbo** [comment]
thanks for fixing that, although now i get the following:
CMake Error: The source directory "/" does not appear to contain CMakeLists.txt

**Comment by Rossobimbo** [comment]
Hi there,

i copied the cmakelists.txt from the YDlidar github into the / folder of the robot PC.
Unfortunately i'm still getting the following error:
The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at //CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


Any ideas?!?
Thanks

**Comment by Rossobimbo** [comment]
for anybody else which might have the same problem, i solved it by running:
sudo apt install build-essential

My current configuration is Ubuntu Server 20.04.3 LTS on a Raspberry Pi 4
