### ISSUE TITLE
Typo in "Optional parameters for simulation on host machine:"

### ISSUE THREAD

**Issue by cpeavy2** [linorobot/linorobot2#19]
ros2 launch linorobo2_description description.launch.py rviz:=true
 
Should read:
ros2 launch linorobot2_description description.launch.py rviz:=true

**Comment by grassjelly** [comment]
fixed with https://github.com/linorobot/linorobot2/commit/f3a9f1ef6cb94eecc4dd791aaa73e1d1273bd5cb . Thanks!
