### ISSUE TITLE
Mecanum and 4wd robots look just the same

### ISSUE THREAD

**Issue by Lindsay284** [linorobot/linorobot2#20]
I want to ask if the two urdf files are the same.... I felt no difference except the depth sensor pose....QAQ

**Comment by grassjelly** [comment]
Appearance is the same, but the macanum's URDF uses this controller https://github.com/linorobot/linorobot2/blob/master/linorobot2_description/urdf/controllers/omni_drive.urdf.xacro so the robot can move holonomically.

**Comment by Lindsay284** [comment]
OK, thanks for your anwsering. This helps me a lot.

> Appearance is the same, but the macanum's URDF uses this controller https://github.com/linorobot/linorobot2/blob/master/linorobot2_description/urdf/controllers/omni_drive.urdf.xacro so the robot can move holonomically.
