### ISSUE TITLE
No Realsense2 package for Galactic

### ISSUE THREAD

**Issue by Russ76** [linorobot/linorobot2#23]
The linorobot2 installer failed because there is no realsense2 package for galactic, only for foxy. After the hiccup, I ran the commands from the installer file one by one in terminal window, and it seemed to install OK.
It wasn't easy to determine if command should be run from linorobot2_ws/src or not!
I'm using Raspi 4 with 4 Gig, 4wd, ydlidar, and realsense.
Juan, thanks for all your hard work putting this together!

There was another error:
HEAD is now at eb322062 Bump version to 1.9.2
/home/ubuntu/linorobot2_ws/src/uros/micro-ROS-Agent/micro_ros_agent/src/agent/graph_manager/graph_manager.cpp: In member function ‘void uros::agent::graph_manager::GraphManager::update_node_entities_info()’:
/home/ubuntu/linorobot2_ws/src/uros/micro-ROS-Agent/micro_ros_agent/src/agent/graph_manager/graph_manager.cpp:584:86: error: ‘ALIVE’ is not a member of ‘eprosima::fastdds::dds::InstanceStateKind’
  584 |         if (sample_info.instance_state == eprosima::fastdds::dds::InstanceStateKind::ALIVE)
      |                                                                                      ^~~~~
In file included from /home/ubuntu/linorobot2_ws/src/uros/micro-ROS-Agent/micro_ros_agent/include/agent/graph_manager/graph_manager.hpp:46,
                 from /home/ubuntu/linorobot2_ws/src/uros/micro-ROS-Agent/micro_ros_agent/src/agent/graph_manager/graph_manager.cpp:18:
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp: In instantiation of ‘void dds_qos_to_rmw_qos(const DDSQoSPolicyT&, rmw_qos_profile_t*) [with DDSQoSPolicyT = eprosima::fastdds::dds::WriterQos; rmw_qos_profile_t = rmw_qos_profile_t]’:
/home/ubuntu/linorobot2_ws/src/uros/micro-ROS-Agent/micro_ros_agent/src/agent/graph_manager/graph_manager.cpp:391:48:   required from here
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:68:19: error: ‘const class eprosima::fastdds::dds::WriterQos’ has no member named ‘reliability’; did you mean ‘m_reliability’?
   68 |   switch (dds_qos.reliability().kind) {
      |           ~~~~~~~~^~~~~~~~~~~
      |           m_reliability
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:80:19: error: ‘const class eprosima::fastdds::dds::WriterQos’ has no member named ‘durability’; did you mean ‘m_durability’?
   80 |   switch (dds_qos.durability().kind) {
      |           ~~~~~~~~^~~~~~~~~~
      |           m_durability
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:92:47: error: ‘const class eprosima::fastdds::dds::WriterQos’ has no member named ‘deadline’; did you mean ‘m_deadline’?
   92 |   qos->deadline = dds_duration_to_rmw(dds_qos.deadline().period);
      |                                       ~~~~~~~~^~~~~~~~
      |                                       m_deadline
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:93:47: error: ‘const class eprosima::fastdds::dds::WriterQos’ has no member named ‘lifespan’; did you mean ‘m_lifespan’?
   93 |   qos->lifespan = dds_duration_to_rmw(dds_qos.lifespan().duration);
      |                                       ~~~~~~~~^~~~~~~~
      |                                       m_lifespan
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:95:19: error: ‘const class eprosima::fastdds::dds::WriterQos’ has no member named ‘liveliness’; did you mean ‘m_liveliness’?
   95 |   switch (dds_qos.liveliness().kind) {
      |           ~~~~~~~~^~~~~~~~~~
      |           m_liveliness
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:107:64: error: ‘const class eprosima::fastdds::dds::WriterQos’ has no member named ‘liveliness’; did you mean ‘m_liveliness’?
  107 |   qos->liveliness_lease_duration = dds_duration_to_rmw(dds_qos.liveliness().lease_duration);
      |                                                        ~~~~~~~~^~~~~~~~~~
      |                                                        m_liveliness
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:109:19: error: ‘const class eprosima::fastdds::dds::WriterQos’ has no member named ‘history’
  109 |   switch (dds_qos.history().kind) {
      |           ~~~~~~~~^~~~~~~
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:120:44: error: ‘const class eprosima::fastdds::dds::WriterQos’ has no member named ‘history’
  120 |   qos->depth = static_cast<size_t>(dds_qos.history().depth);
      |                                    ~~~~~~~~^~~~~~~
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp: In instantiation of ‘void dds_qos_to_rmw_qos(const DDSQoSPolicyT&, rmw_qos_profile_t*) [with DDSQoSPolicyT = eprosima::fastdds::dds::ReaderQos; rmw_qos_profile_t = rmw_qos_profile_t]’:
/home/ubuntu/linorobot2_ws/src/uros/micro-ROS-Agent/micro_ros_agent/src/agent/graph_manager/graph_manager.cpp:446:48:   required from here
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:68:19: error: ‘const class eprosima::fastdds::dds::ReaderQos’ has no member named ‘reliability’; did you mean ‘m_reliability’?
   68 |   switch (dds_qos.reliability().kind) {
      |           ~~~~~~~~^~~~~~~~~~~
      |           m_reliability
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:80:19: error: ‘const class eprosima::fastdds::dds::ReaderQos’ has no member named ‘durability’; did you mean ‘m_durability’?
   80 |   switch (dds_qos.durability().kind) {
      |           ~~~~~~~~^~~~~~~~~~
      |           m_durability
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:92:47: error: ‘const class eprosima::fastdds::dds::ReaderQos’ has no member named ‘deadline’; did you mean ‘m_deadline’?
   92 |   qos->deadline = dds_duration_to_rmw(dds_qos.deadline().period);
      |                                       ~~~~~~~~^~~~~~~~
      |                                       m_deadline
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:93:47: error: ‘const class eprosima::fastdds::dds::ReaderQos’ has no member named ‘lifespan’; did you mean ‘m_lifespan’?
   93 |   qos->lifespan = dds_duration_to_rmw(dds_qos.lifespan().duration);
      |                                       ~~~~~~~~^~~~~~~~
      |                                       m_lifespan
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:95:19: error: ‘const class eprosima::fastdds::dds::ReaderQos’ has no member named ‘liveliness’; did you mean ‘m_liveliness’?
   95 |   switch (dds_qos.liveliness().kind) {
      |           ~~~~~~~~^~~~~~~~~~
      |           m_liveliness
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:107:64: error: ‘const class eprosima::fastdds::dds::ReaderQos’ has no member named ‘liveliness’; did you mean ‘m_liveliness’?
  107 |   qos->liveliness_lease_duration = dds_duration_to_rmw(dds_qos.liveliness().lease_duration);
      |                                                        ~~~~~~~~^~~~~~~~~~
      |                                                        m_liveliness
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:109:19: error: ‘const class eprosima::fastdds::dds::ReaderQos’ has no member named ‘history’
  109 |   switch (dds_qos.history().kind) {
      |           ~~~~~~~~^~~~~~~
/opt/ros/galactic/include/rmw_fastrtps_shared_cpp/qos.hpp:120:44: error: ‘const class eprosima::fastdds::dds::ReaderQos’ has no member named ‘history’
  120 |   qos->depth = static_cast<size_t>(dds_qos.history().depth);
      |                                    ~~~~~~~~^~~~~~~
make[5]: *** [CMakeFiles/micro_ros_agent.dir/build.make:89: CMakeFiles/micro_ros_agent.dir/src/agent/graph_manager/graph_manager.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/Makefile2:78: CMakeFiles/micro_ros_agent.dir/all] Error 2
make[3]: *** [Makefile:141: all] Error 2
make[2]: *** [CMakeFiles/micro_ros_agent.dir/build.make:113: micro_ros_agent-prefix/src/micro_ros_agent-stamp/micro_ros_agent-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/micro_ros_agent.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
---
Failed   <<< micro_ros_agent [11min 43s, exited with code 2]

Summary: 1 package finished [12min 18s]
  1 package failed: micro_ros_agent
  1 package had stderr output: micro_ros_agent

A little later:

make: *** [Makefile:141: all] Error 2
---
Failed   <<< micro_ros_agent [25.3s, exited with code 2]
Aborted  <<< drive_base_msgs [1min 16s]                                        

Summary: 7 packages finished [1min 17s]
  1 package failed: micro_ros_agent
  1 package aborted: drive_base_msgs
  1 package had stderr output: micro_ros_agent
  1 package not processed

**Comment by grassjelly** [comment]
1. Delete all micro-ros related packages including the ros2.repos on ws/src dir.
2. Reinstall micro-ros as mentioned here: https://github.com/linorobot/linorobot2/blob/master/ROBOT_INSTALLATION.md#14-download-and-install-micro-ros

If continues to fail, redo 1 and delete your ws's build and install folder then proceed to 2.

**Comment by Russ76** [comment]
I was able to get it installed correctly! And prepared the host. Haven't finished hardware yet. It looks like a world-wide shortage of Raspberry Pi 4 - 8 Gig models!
