### ISSUE TITLE
Using ODrive

### ISSUE THREAD

**Issue by qiwalker** [linorobot/linorobot2#28]
Hi,

is it possible to use ODrive driver with linorobot ?

Thankyou..

**Comment by Sylvania2** [comment]
Hi

ODRIVE Interface:
Servo PWM -- RC Recievers, Arduino, etc.

I am using VESC4 and they are working fine.

Best regards

**Comment by qiwalker** [comment]
Hi, 

thanks for your reply, so is it possible to use with Linorobot with teensy ?
btw do you have partnumber for your VESC4 ?

this is the motor i use, will it work with VESC4 ?, i already try using Odrive and it working.
![image](https://user-images.githubusercontent.com/45870169/165455813-ac7179d6-ab39-4a8e-bf2d-a2ce36d6de6e.png)

this is the Odrive 3.6 for the driver
![image](https://user-images.githubusercontent.com/45870169/165456388-cd53f68b-ad51-4202-ab8c-e15509f847f5.png)


thankyou

**Comment by Sylvania2** [comment]
Just google vesc4 or a clone like fsesc4..
https://flipsky.net/products/mini-fsesc4-20-50a-base-on-vesc-widely-used-in-eskateboard-escooter-ebike

Best regards


Den ons. 27. apr. 2022 kl. 08.34 skrev qiwalker ***@***.***>:

**Comment by qiwalker** [comment]
hi, anyone now how to read hall sensor as an encoder ?
brushless motor already include the hall sensor for encoder, but i have no idea how to read this as a encoder output

thanks

**Comment by grassjelly** [comment]
closing this for now. Please open a separate issue on linorobot2_hardware on hardware related questions. Thanks!
