### ISSUE TITLE
When running RVIZ, getting Global Status Error: No tf data. Actual error: Frame [base_footprint] does not exist

### ISSUE THREAD

**Issue by philmurp** [linorobot/linorobot2#3]
This is occurring when I am trying to visualize the URDF on host computer.

At this same time, the robot computer is stuck at the below status:

`joint_state_publisher: Waiting for robot_description to be published on the robot_description topic`

**Comment by grassjelly** [comment]
‘Waiting for robot_description to be published …’ is normal. Please refer to the photo of a working demo here: https://github.com/linorobot/linorobot2/issues/2#issuecomment-936118904
