### ISSUE TITLE
Teensy 4.1 Firmware Load

### ISSUE THREAD

**Issue by longwm** [linorobot/linorobot2#32]
Getting the following error when I try to load the firmware to a teensy41.

Compiling .pio/build/teensy41/lib443/imu/ADXL345.cpp.o
In file included from /home/jetson/linorobot2_hardware/firmware/src/firmware.ino:32:0:
lib/odometry/odometry.h:19:48: fatal error: micro_ros_utilities/type_utilities.h: No such file or directory
compilation terminated.
Compiling .pio/build/teensy41/lib443/imu/HMC5883L.cpp.o
*** [.pio/build/teensy41/src/firmware.ino.cpp.o] Error 1
========================= [FAILED] Took 17.60 seconds =========================

Environment    Status    Duration
-------------  --------  ------------
teensy41       FAILED    00:00:17.599
==================== 1 failed, 0 succeeded in 00:00:17.599 ====================

Please advise. Thank you

**Comment by grassjelly** [comment]
Hi, could you post this to the hardware repository instead? https://github.com/linorobot/linorobot2_hardware/issues Closing this for now.
