### ISSUE TITLE
slam toolbox, RobotModel Status : Error

### ISSUE THREAD

**Issue by hwacoding** [linorobot/linorobot2#33]
$  ros2 launch linorobot2_description description.launch.py rviz:=true
I can see my robot.

But, When I doing slam.
$ ros2 launch linorobot2_navigation slam.launch.py rviz:=true sim:=true
![1](https://user-images.githubusercontent.com/105493201/177096842-cb792033-1011-4261-83fe-00bed1edd514.PNG)
![2](https://user-images.githubusercontent.com/105493201/177096849-024bc0fe-588e-4d8e-a4db-f2d69b93baa0.PNG)

There are no RobotModel base_footprint and base_link else.
But, I can see these when I 
$  ros2 launch linorobot2_description description.launch.py rviz:=true

Also, I  [slam_toolbox]: Message Filter dropping message: frame 'laser'
So I try follow this.

Try to up transform_timeout by 0.1 in linorobot2_navigation/config/slam.yaml until the warning is gone.

But, I this Message keep showing.

Please help me.

**Comment by grassjelly** [comment]
hey @hwacoding. Could you reply this pls. https://github.com/linorobot/linorobot2_hardware/issues/13

**Comment by hwacoding** [comment]
Ok. sorry. I reply it now.

**Comment by hwacoding** [comment]
![image](https://user-images.githubusercontent.com/105493201/177106617-7011402e-e9aa-44cc-8ffb-a4735625ebce.png)
/robot_description topic have to go /ekf_filter_node?

**Comment by grassjelly** [comment]
Don't use the sim argument if you're mapping using the real robot. 
`ros2 launch linorobot2_navigation slam.launch.py rviz:=true`
