### ISSUE TITLE
Gazebo install fails on RPi / U22 Jammy / ROS2 Humble

### ISSUE THREAD

**Issue by JHPHELAN** [linorobot/linorobot2#38]
ubuntu@LINOROBOT:/tmp$ **bash install_linorobot2.bash 4wd ydlidar realsense**
...
E: Unable to locate package ros-humble-gazebo-ros-pkgs
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-humble-gazebo-ros-pkgs] failed

Trying directly:
ubuntu@LINOROBOT:/tmp$ **sudo -H apt-get install -y ros-humble-gazebo-ros-pkgs**
also fails

according to [https://github.com/ros-simulation/gazebo_ros_pkgs/issues/1158](url)
chapulina commented on Sep 9, 2020
Board: Raspberry Pi4 4Gb of RAM
ros foxy on a Rpi4
**This is the problem, gazebo-ros-pkgs is only available for amd64:**

Confirmed by looking in:
[http://packages.ros.org/ros2/ubuntu/pool/main/r/ros-foxy-gazebo-ros-pkgs/](url)

ros-<distro>-desktop-full is reported to contain gazebo.  It is NOT available.  
whereas ros-<distro>-desktop does not.  IS available for humble.
**Need a work-around to install gazebo under ROS2 Humble / U22 Jammy  / Raspberry Pi 4B-8GB**

**Comment by samuk** [comment]
Yeah I just ran into this too 

ubuntu@ubuntu:~$ sudo -H apt-get install -y ros-humble-gazebo-ros-pkgs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ros-humble-gazebo-ros-pkgs

**Comment by samuk** [comment]
This looks relevant: https://github.com/osrf/gazebo/issues/3236#issuecomment-1204137725

**Comment by samuk** [comment]
There is now a PPA listed here: https://github.com/osrf/gazebo/issues/3236 that allows you to install Gazebo on a Pi. However the script still fails to run as ros-humble-gazebo-ros-pkgs doesn't exist.

**Comment by samuk** [comment]
It looks like ros-humble-gazebo-ros-pkgs will never exist officially for Arm. Workarounds here: https://github.com/gazebosim/gazebo-classic/issues/3236#issuecomment-1331053760

Essentially just add the PPA https://launchpad.net/~openrobotics/+archive/ubuntu/gazebo11-non-amd64

**Comment by grassjelly** [comment]
Hey @samuk I don't think it's also ideal to run Gazebo on PI anyway.
