### ISSUE TITLE
"Odom frame not found" when launching navigation and joint state publisher stuck on waiting to publish robot_description topic

### ISSUE THREAD

**Issue by zyongye** [linorobot/linorobot2#45]
Hi, I'm following the quick start linorobot2 and run exact the same install command except replace "micro-ros-agent" to my own node to process "/cmd_vel" topics. However, the following two message keeping showing up and the rviz keeping showing no transform from all part to "map" topics. 

When I run nav2 package, 

![Screenshot from 2022-08-31 18-30-42](https://user-images.githubusercontent.com/42426329/187803203-b1a0a43f-f33c-4d90-aae8-f1f8b9a0b38e.png)

When I run bring_up. 

![Screenshot from 2022-08-31 18-34-14](https://user-images.githubusercontent.com/42426329/187803121-b2d208aa-207a-4795-be6d-32d955878514.png)

![Screenshot from 2022-08-31 18-41-36](https://user-images.githubusercontent.com/42426329/187803623-41559b32-96c7-4c07-a792-18e2f96020fd.png)

Any help is appreciated!!!

Thanks in advance!!!

**Comment by grassjelly** [comment]
can you confirm the following? https://github.com/linorobot/linorobot2_hardware#3-check-the-topics

**Comment by zyongye** [comment]
Yeah they are all present. 
![Screenshot from 2022-08-31 20-36-22](https://user-images.githubusercontent.com/42426329/187813798-bbe91dc8-e954-424c-856b-e90167e7db94.png)

**Comment by zyongye** [comment]
Also I only use laser sensor...

**Comment by grassjelly** [comment]
are you able to echo odom topic?

**Comment by zyongye** [comment]
Yeah there's no any other output..

**Comment by grassjelly** [comment]
could you post the issue on linorobot2_hardware instead?

**Comment by thanhtruongphan** [comment]
excuse me, @zyongye did you solve it? pls
