### ISSUE TITLE
Unable to locate package ros-foxy-realsense2-camera

### ISSUE THREAD

**Issue by nuitvolgit** [linorobot/linorobot2#6]
Hello,

I use ROS2 foxy with Ubuntu 20.04 and the realsens is my target sensor.
When I tried to install, I got "E: Unable to locate package ros-foxy-realsense2-camera".

I tried "sudo apt install ros-foxy-realsense2-camera" but I got
"E: Unable to locate package ros-foxy-realsense2-camera".
Is there any way to install the realsens2-camera package for ROS2 foxy?

Thanks.

**Comment by grassjelly** [comment]
binary should be available for realsense2. Can you do an upgrade?

`sudo apt install upgrade`

and install again?

**Comment by nuitvolgit** [comment]
Doesn't work.
I guess it is not the linorobot package problem so I will close this.
Thanks anyway!
