### ISSUE TITLE
Linorobot2 wrapper for other 4 wheel robots

### ISSUE THREAD

**Issue by brianlmerritt** [linorobot/linorobot2#63]
I can't remember whether it was a pull request here or on another repo, but I vaguely remember someone adding a wrapper for linorobot2 so it can be more easily used for other robots.  Is that the case for robots with different motor controller boards and imu sensors?

**Comment by grassjelly** [comment]
You can find it here: https://github.com/linorobot/linorobot2/blob/galactic/linorobot2_bringup/launch/custom_robot.launch.py . This launches a Sphere RVR robot by setting custom_robot to True when launching bringup.launch.py

**Comment by brianlmerritt** [comment]
Thanks!
