### ISSUE TITLE
minium HW required

### ISSUE THREAD

**Issue by tbop-R** [linorobot/linorobot2#68]
What are the minimum hardware requirements?
I have a raspberry PI 3, orange pc, Teensy 3.2 and a kinect sensor v1.
Do you recommend using ROS2 or ROS1?

Thank you

**Comment by grassjelly** [comment]
Hi, this only runs on ROS2

**Comment by tbop-R** [comment]
Where can I find a guide to compile ROS2 in debian ARM 32 bit?
Thank you
