### ISSUE TITLE
32-bit support?

### ISSUE THREAD

**Issue by tbop-R** [linorobot/linorobot2#72]
Can Linorobot 2 and ROS 2 be installed on a 32 bit ARM like raspberry PI2 or orange PI?

Thank you

**Comment by grassjelly** [comment]
I think it’s technically possible. However I haven’t personally tried running Nav2 on pi2 so can’t comment much on the performance

**Comment by tbop-R** [comment]
Where can I find a guide to compile ROS2 in debian ARM 32 bit?
Thank you

**Comment by grassjelly** [comment]
you can check out the hardware repo here https://github.com/linorobot/linorobot2_hardware

**Comment by grassjelly** [comment]
closing this for now. feel free to open if needed. Thanks
